set_property PACKAGE_PIN J13 [get_ports Rstn_i]
set_property IOSTANDARD LVCMOS33 [get_ports Rstn_i]
set_property PACKAGE_PIN G14 [get_ports {LED[0]}]
set_property PACKAGE_PIN H14 [get_ports {LED[1]}]
set_property PACKAGE_PIN J10 [get_ports {LED[2]}]
set_property PACKAGE_PIN J11 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[*]}]
#BTN
set_property PACKAGE_PIN J13 [get_ports {BTN[0]}]
set_property PACKAGE_PIN H13 [get_ports {BTN[1]}]
set_property PACKAGE_PIN H9 [get_ports {BTN[2]}]
set_property PACKAGE_PIN H8 [get_ports {BTN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BTN[*]}]

#power up
set_property PACKAGE_PIN V21 [get_ports USBSS_EN]
set_property IOSTANDARD LVCMOS33 [get_ports USBSS_EN]

#ft60x pin

create_clock -period 10.000 -name CLK_i -waveform {0.000 5.000} [get_ports CLK_i]
set_property PACKAGE_PIN N21 [get_ports CLK_i]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_i]

set_property PACKAGE_PIN T25 [get_ports RXF_N_i]
set_property IOSTANDARD LVCMOS33 [get_ports RXF_N_i]

set_property PACKAGE_PIN N26 [get_ports TXE_N_i]
set_property IOSTANDARD LVCMOS33 [get_ports TXE_N_i]

set_property PACKAGE_PIN P26 [get_ports WR_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports WR_N_o]

set_property PACKAGE_PIN R26 [get_ports RD_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports RD_N_o]

set_property PACKAGE_PIN V26 [get_ports OE_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports OE_N_o]

set_property PACKAGE_PIN U26 [get_ports WAKEUP_o]
set_property IOSTANDARD LVCMOS33 [get_ports WAKEUP_o]

set_property PACKAGE_PIN T24 [get_ports SIWU_N_o]
set_property IOSTANDARD LVCMOS33 [get_ports SIWU_N_o]

set_property PACKAGE_PIN U25 [get_ports {GPIO_o[0]}]
set_property PACKAGE_PIN U24 [get_ports {GPIO_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_o[*]}]

set_property PACKAGE_PIN K26 [get_ports {DATA_io[0]}]
set_property PACKAGE_PIN K25 [get_ports {DATA_io[1]}]
set_property PACKAGE_PIN L25 [get_ports {DATA_io[2]}]
set_property PACKAGE_PIN M25 [get_ports {DATA_io[3]}]
set_property PACKAGE_PIN L24 [get_ports {DATA_io[4]}]
set_property PACKAGE_PIN M24 [get_ports {DATA_io[5]}]
set_property PACKAGE_PIN N24 [get_ports {DATA_io[6]}]
set_property PACKAGE_PIN P24 [get_ports {DATA_io[7]}]
set_property PACKAGE_PIN M22 [get_ports {DATA_io[8]}]
set_property PACKAGE_PIN M21 [get_ports {DATA_io[9]}]
set_property PACKAGE_PIN N22 [get_ports {DATA_io[10]}]
set_property PACKAGE_PIN M20 [get_ports {DATA_io[11]}]
set_property PACKAGE_PIN N19 [get_ports {DATA_io[12]}]
set_property PACKAGE_PIN M19 [get_ports {DATA_io[13]}]
set_property PACKAGE_PIN N18 [get_ports {DATA_io[14]}]
set_property PACKAGE_PIN P18 [get_ports {DATA_io[15]}]
set_property PACKAGE_PIN R18 [get_ports {DATA_io[16]}]
set_property PACKAGE_PIN R17 [get_ports {DATA_io[17]}]
set_property PACKAGE_PIN R16 [get_ports {DATA_io[18]}]
set_property PACKAGE_PIN N17 [get_ports {DATA_io[19]}]
set_property PACKAGE_PIN P16 [get_ports {DATA_io[20]}]
set_property PACKAGE_PIN R20 [get_ports {DATA_io[21]}]
set_property PACKAGE_PIN T20 [get_ports {DATA_io[22]}]
set_property PACKAGE_PIN U20 [get_ports {DATA_io[23]}]
set_property PACKAGE_PIN U19 [get_ports {DATA_io[24]}]
set_property PACKAGE_PIN T19 [get_ports {DATA_io[25]}]
set_property PACKAGE_PIN T18 [get_ports {DATA_io[26]}]
set_property PACKAGE_PIN T23 [get_ports {DATA_io[27]}]
set_property PACKAGE_PIN T22 [get_ports {DATA_io[28]}]
set_property PACKAGE_PIN T17 [get_ports {DATA_io[29]}]
set_property PACKAGE_PIN U17 [get_ports {DATA_io[30]}]
set_property PACKAGE_PIN V22 [get_ports {DATA_io[31]}]

set_property IOSTANDARD LVCMOS33 [get_ports {DATA_io[*]}]
set_property PULLUP true [get_ports {DATA_io[0]}]
set_property PULLUP true [get_ports {DATA_io[1]}]
set_property PULLUP true [get_ports {DATA_io[2]}]
set_property PULLUP true [get_ports {DATA_io[3]}]
set_property PULLUP true [get_ports {DATA_io[4]}]
set_property PULLUP true [get_ports {DATA_io[5]}]
set_property PULLUP true [get_ports {DATA_io[6]}]
set_property PULLUP true [get_ports {DATA_io[7]}]
set_property PULLUP true [get_ports {DATA_io[8]}]
set_property PULLUP true [get_ports {DATA_io[9]}]
set_property PULLUP true [get_ports {DATA_io[10]}]
set_property PULLUP true [get_ports {DATA_io[11]}]
set_property PULLUP true [get_ports {DATA_io[12]}]
set_property PULLUP true [get_ports {DATA_io[13]}]
set_property PULLUP true [get_ports {DATA_io[14]}]
set_property PULLUP true [get_ports {DATA_io[15]}]
set_property PULLUP true [get_ports {DATA_io[16]}]
set_property PULLUP true [get_ports {DATA_io[17]}]
set_property PULLUP true [get_ports {DATA_io[18]}]
set_property PULLUP true [get_ports {DATA_io[19]}]
set_property PULLUP true [get_ports {DATA_io[20]}]
set_property PULLUP true [get_ports {DATA_io[21]}]
set_property PULLUP true [get_ports {DATA_io[22]}]
set_property PULLUP true [get_ports {DATA_io[23]}]
set_property PULLUP true [get_ports {DATA_io[24]}]
set_property PULLUP true [get_ports {DATA_io[25]}]
set_property PULLUP true [get_ports {DATA_io[26]}]
set_property PULLUP true [get_ports {DATA_io[27]}]
set_property PULLUP true [get_ports {DATA_io[28]}]
set_property PULLUP true [get_ports {DATA_io[29]}]
set_property PULLUP true [get_ports {DATA_io[30]}]
set_property PULLUP true [get_ports {DATA_io[31]}]

set_property IOSTANDARD LVCMOS33 [get_ports {BE_io[*]}]
set_property PACKAGE_PIN P19 [get_ports {BE_io[0]}]
set_property PACKAGE_PIN R23 [get_ports {BE_io[1]}]
set_property PACKAGE_PIN R22 [get_ports {BE_io[2]}]
set_property PACKAGE_PIN M26 [get_ports {BE_io[3]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]




